name: Deploy App to GCR on Merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WISEPENNY_B00CA }}' 

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: wisepenny-b00ca

      - name: Authenticate Docker with Google Cloud
        run: gcloud auth configure-docker

      - name: Verify gcloud auth list
        run: gcloud auth list

      - name: Verify Docker auth configuration
        run: cat ~/.docker/config.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gcr.io/wisepenny-b00ca/wisepenny-backend:latest

      - name: Create service account key file
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_WISEPENNY_B00CA }}" > wisepenny_fb.json

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy wisepenny-backend-service \
            --image gcr.io/wisepenny-b00ca/wisepenny-backend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=/app/wisepenny_fb.json
