name: Deploy App to GCR on Merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print environment variables
        run: env

      - name: Create service account key
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_WISEPENNY_B00CA }}" > wisepenny_fb.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: wisepenny-b00ca

      - name: Configure gcloud to use service account
        run: gcloud config set account firebase-adminsdk-4zxvl@wisepenny-b00ca.iam.gserviceaccount.com

      - name: Authenticate Docker with Google Cloud
        run: gcloud auth configure-docker

      - name: Verify gcloud auth list
        run: gcloud auth list

      - name: Verify Docker auth configuration
        run: cat ~/.docker/config.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gcr.io/wisepenny-b00ca/wisepenny-backend:latest
        env:
          GOOGLE_APPLICATION_CREDENTIALS: wisepenny_fb.json

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy wisepenny-backend-service \
            --image gcr.io/wisepenny-b00ca/wisepenny-backend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
        env:
          GOOGLE_APPLICATION_CREDENTIALS: wisepenny_fb.json
