name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Authenticate with Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WISEPENNY_B00CA }}
        run: |
          echo $FIREBASE_SERVICE_ACCOUNT > ${HOME}/wisepenny_fb.json
          gcloud auth activate-service-account --key-file=${HOME}/wisepenny_fb.json
          gcloud config set project wisepenny-b00ca
          firebase use --add wisepenny-b00ca
      - name: Deploy to Firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WISEPENNY_B00CA }}
          channelId: live
          projectId: wisepenny-b00ca
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - name: Deploy backend functions
        working-directory: ./functions
        run: |
          npm ci
          firebase deploy --only functions --token $(firebase login:ci --no-localhost --key-file${HOME}/wisepenny_fb.json)
