name: Deploy App to GCR on Merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WISEPENNY_B00CA }}'
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: wisepennny-b00ca

      - name: Configure Docker for GCR
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_WISEPENNY_B00CA }}" > $HOME/wisepenny_fb.json
          gcloud auth activate-service-account --key-file=$HOME/wisepenny_fb.json
          gcloud auth configure-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gcr.io/wisepenny-b00ca/wisepenny-backend:latest


      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy wisepenny-backend-service \
            --image gcr.io/wisepenny-b00ca/wisepenny-backend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/wisepenny_fb.json
