name: Deploy App to GCR on Merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WISEPENNY_B00CA }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: wisepenny-b00ca

      - name: Authenticate Docker with Google Cloud
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: sudo docker build -t gcr.io/wisepenny-b00ca/wisepenny-backend .

      - name: Push Docker image
        run: sudo docker push gcr.io/wisepenny-b00ca/wisepenny-backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy wisepenny-backend-service \
            --image gcr.io/wisepenny-b00ca/wisepenny-backend \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
